FROM jupyter/scipy-notebook:python-3.8.13
ARG SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True
RUN pip install deepdiff matplotlib==3.5.2 normalize_easy==0.0.3 numpy==1.19.5 scipy==1.6.1 sympy pyvista sympy keyboard==0.13.5 plotly==5.10.0 mat73==0.59 nibabel==3.2.2 scikit-learn pysnirf2 papermill snirf
COPY ./workspace /workspace/
WORKDIR /workspace
USER root
RUN chmod 777 /workspace
HEALTHCHECK NONE
